name: 'manager'

services:

  postgresql:
    image: 'postgres:15-alpine'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=manager
    ports:
      - '127.0.0.1:5432:5432'
